services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data_practice:/var/lib/mysql
    ports:
      - 13307:13306
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/Group2
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      DATABASE_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:4445/wd/hub
    ports:
      - "3001:3001"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4445:4445
volumes:
  mysql_data_practice:
  bundle_data:
  node_modules:
